apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: customerapphelmbased
  namespace: argocd

spec:
  project: default

  source:
    repoURL: "acrwinter.azurecr.io/helm"
    chart: "helm-nginx"
    targetRevision: 0.34.0

    

  destination:
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

   